name: Deploy PR Environment with ngrok

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Start Backend
        run: |
          cd backend
          nohup node index.js &

      - name: Start ngrok and persist
        run: |
          nohup npx ngrok http 3001 --authtoken ${{ secrets.NGROK_AUTH_TOKEN }} &

      - name: Wait and Get ngrok URL
        run: |
          sleep 10 # ngrok'un başlatılması için bekleme
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url